export type SearchMode = 'text'|'image'|'face'|'video'|'document'|'archive'|'metadata';
export interface SearchRequest { id:string; mode:SearchMode; query?:string; imageUrl?:string; filters?:{domains?:string[];excludeDomains?:string[];dateFrom?:string;dateTo?:string;languages?:string[];countries?:string[];sourceTypes?:string[]}; budget?:{maxJobs?:number;maxDepth?:number;timeoutMs?:number;maxProviderCostUsd?:number} }
export interface SearchObservation { id:string; provider:string; providerResultId?:string; sourceUrl?:string; mediaUrl?:string; title?:string; snippet?:string; discoveredAt:string; publishedAt?:string; sourceType?:string; queryJobId:string; providerScore?:number; signals?:Record<string,number>; entities?:Array<{type:string;value:string;confidence?:number}>; provenance?:Array<{relation:string;targetObservationId:string}> }
export interface SearchAdapter { readonly id:string; readonly modes:readonly SearchMode[]; isAvailable():Promise<boolean>; search(request:SearchRequest):Promise<SearchObservation[]> }
export class AdapterRegistry { private readonly adapters=new Map<string,SearchAdapter>(); register(adapter:SearchAdapter){if(this.adapters.has(adapter.id))throw new Error(`Adapter already registered: ${adapter.id}`);this.adapters.set(adapter.id,adapter)} registerMany(adapters:SearchAdapter[]){for(const adapter of adapters)this.register(adapter)} list(mode?:SearchMode){const all=[...this.adapters.values()];return mode?all.filter(a=>a.modes.includes(mode)):all} }
export function normalizeObservations(items:SearchObservation[]){const seen=new Set<string>();return items.filter(item=>{const key=item.mediaUrl??item.sourceUrl??`${item.provider}:${item.providerResultId??item.id}`;if(seen.has(key))return false;seen.add(key);return true})}
export function rankObservation(item:SearchObservation){const values=Object.values(item.signals??{}).filter((v):v is number=>typeof v==='number');return values.length?values.reduce((a,b)=>a+b,0)/values.length:(item.providerScore??0)}
export interface SearchPlanStep {mode:SearchMode;reason:string;depth:number;capabilities?:string[]}
export function buildSearchPlan(request:SearchRequest):SearchPlanStep[]{const steps:SearchPlanStep[]=[{mode:request.mode,reason:'primary query',depth:0}];if(request.mode==='image')steps.push({mode:'metadata',reason:'extract metadata and clues',depth:1},{mode:'archive',reason:'find historical copies',depth:1},{mode:'document',reason:'search embedded imagery',depth:1});if(request.mode==='face')steps.push({mode:'image',reason:'expand visual candidates',depth:1},{mode:'metadata',reason:'extract captions and dates',depth:1},{mode:'archive',reason:'search historical photographs',depth:1});if(request.mode==='video')steps.push({mode:'face',reason:'search keyframes',depth:1},{mode:'image',reason:'search representative frames',depth:1});if(request.mode==='text'||request.mode==='archive')steps.push({mode:'archive',reason:'historical indexes',depth:1,capabilities:['wayback','common-crawl']},{mode:'text',reason:'configured public newsgroups',depth:1,capabilities:['nntp']},{mode:'text',reason:'configured public FTP sources',depth:1,capabilities:['ftp']});return steps.filter(s=>s.depth<=(request.budget?.maxDepth??2))}
export interface EvidenceCluster {key:string;observations:SearchObservation[];providerCount:number;domainCount:number;score:number}
export function clusterSearchEvidence(items:SearchObservation[]):EvidenceCluster[]{const groups=new Map<string,SearchObservation[]>();for(const item of items){const key=item.mediaUrl??item.sourceUrl??`${item.provider}:${item.id}`;const group=groups.get(key)??[];group.push(item);groups.set(key,group)}return [...groups].map(([key,observations])=>{const providers=new Set(observations.map(x=>x.provider));const domains=new Set(observations.map(x=>{try{return x.sourceUrl?new URL(x.sourceUrl).hostname:x.provider}catch{return x.provider}}));return{key,observations,providerCount:providers.size,domainCount:domains.size,score:Math.min(1,.5+providers.size*.15+domains.size*.05)}}).sort((a,b)=>b.score-a.score)}
export async function executeSearch(request:SearchRequest,registry:AdapterRegistry):Promise<SearchObservation[]>{const adapters=registry.list(request.mode);const available=await Promise.all(adapters.map(async adapter=>({adapter,available:await adapter.isAvailable()})));const jobs=available.filter(x=>x.available).slice(0,request.budget?.maxJobs??available.length).map(({adapter})=>Promise.race([adapter.search(request),new Promise<SearchObservation[]>((_,reject)=>setTimeout(()=>reject(new Error(`adapter timeout: ${adapter.id}`)),request.budget?.timeoutMs??15000))]));const batches=await Promise.allSettled(jobs);return normalizeObservations(batches.flatMap(r=>r.status==='fulfilled'?r.value:[])).sort((a,b)=>rankObservation(b)-rankObservation(a))}
