export type AgentRisk = 'LOW'|'MODERATE'|'HIGH'|'CRITICAL';
export interface AgentPermission {agentId:string;capability:string;scope:string;decision:'ALLOW'|'DENY'|'ASK';reason:string;expiresAt?:number}
export interface AgentTask {id:string;workflowId:string;agentId:string;objective:string;risk:AgentRisk;budget:{maxToolCalls:number;timeoutMs:number;maxCostUsd?:number};requiresApproval?:boolean}
export interface AgentExecution {id:string;taskId:string;operation:string;target?:string;allowed:boolean;ok:boolean;durationMs:number;createdAt:number;error?:string}
export interface AgentRuntimeAdapter {execute(task:AgentTask,operation:string,target?:string):Promise<{ok:boolean;result?:unknown;error?:string}>}
export class AgentPermissionGate {private readonly permissions:AgentPermission[]=[];grant(permission:AgentPermission){this.permissions.push(permission)}check(agentId:string,capability:string,scope:string):AgentPermission['decision']{const matches=this.permissions.filter(p=>p.agentId===agentId&&p.capability===capability&&p.scope===scope&&(!p.expiresAt||p.expiresAt>Date.now()));return matches.at(-1)?.decision??'DENY'}}
export class AgentRuntime {constructor(private readonly gate=new AgentPermissionGate()){} private readonly executions:AgentExecution[]=[]; get permissionGate(){return this.gate} async run(task:AgentTask,operation:string,target?:string){if(task.requiresApproval&&task.risk!=='LOW')return{ok:false,error:'Explicit approval required'};const permission=this.gate.check(task.agentId,operation,target??'GLOBAL');if(permission!=='ALLOW')return{ok:false,error:permission==='ASK'?'Permission requires approval':'Permission denied'};return{ok:true}} record(execution:AgentExecution){this.executions.push(execution)} history(taskId?:string){return this.executions.filter(e=>!taskId||e.taskId===taskId)}}
export interface CapabilityNeed {id:string;name:string;required:string[];preferred:string[];forbidden:string[];risk:AgentRisk}
export interface CapabilityMatch {capabilityId:string;score:number;reasons:string[];warnings:string[]}
export function scoreCapability(need:CapabilityNeed,provided:{id:string;capabilities:string[];risk:AgentRisk;status:string}):CapabilityMatch{const have=new Set(provided.capabilities.map(x=>x.toLowerCase()));const required=need.required.filter(x=>!have.has(x.toLowerCase()));const preferred=need.preferred.filter(x=>have.has(x.toLowerCase()));const forbidden=need.forbidden.filter(x=>have.has(x.toLowerCase()));let score=required.length?0:0.6+preferred.length*0.1-forbidden.length*0.25;if(provided.status==='TRUSTED')score+=0.1;return{capabilityId:provided.id,score:Math.max(0,Math.min(1,score)),reasons:[required.length?'missing required capability':'all required capabilities present',`${preferred.length} preferred capabilities matched`],warnings:forbidden.map(x=>`Forbidden capability present: ${x}`)}}
