export type MissingInfoCategory = 'deadline'|'identity'|'amount'|'date'|'document'|'address'|'evidence'|'procedural'|'recipient'|'other';
export type MissingInfoImpact = 'blocking'|'high'|'medium'|'low';
export type MissingInfoStatus = 'missing'|'provided'|'not_applicable'|'deferred';
export interface MissingInfoItem { id:string; category:MissingInfoCategory; field:string; label:string; whyItMatters:string; impact:MissingInfoImpact; status:MissingInfoStatus; suggestedActions:string[]; relatedFactId?:string; resolvedValue?:string; resolvedAt?:string; createdAt:string; }
export interface MissingInfoInput { facts:{id:string;label:string;value:string;confidence:number;verified:boolean}[]; deadline?:{date?:string;certainty:string}; agency?:string; referenceNumber?:string; noticeDate?:string; recipient?:{name?:string;address?:string}; evidenceCount:number; }
export function createMissingInfo(input: Omit<MissingInfoItem,'id'|'status'|'createdAt'>): MissingInfoItem { return { ...input, id: crypto.randomUUID(), status:'missing', createdAt:new Date().toISOString() }; }
export function detectMissingInfo(input: MissingInfoInput): MissingInfoItem[] { const items:MissingInfoItem[]=[]; if(!input.deadline?.date||input.deadline.certainty==='missing') items.push(createMissingInfo({category:'deadline',field:'response_deadline',label:'Response deadline',whyItMatters:'Without a reliable deadline, urgency cannot be assessed safely.',impact:'blocking',suggestedActions:['Review the notice for deadline language','Verify an ambiguous deadline with the issuing authority']})); if(!input.agency) items.push(createMissingInfo({category:'identity',field:'issuing_agency',label:'Issuing agency',whyItMatters:'The agency determines routing and applicable correspondence requirements.',impact:'blocking',suggestedActions:['Check the notice letterhead']})); if(!input.referenceNumber) items.push(createMissingInfo({category:'identity',field:'reference_number',label:'Case/reference number',whyItMatters:'The response may need a reliable identifier to be matched to the case.',impact:'high',suggestedActions:['Check the notice header']})); if(!input.noticeDate) items.push(createMissingInfo({category:'date',field:'notice_date',label:'Notice date',whyItMatters:'The notice date may be needed for chronology and deadline analysis.',impact:'medium',suggestedActions:['Check the first page for the notice date']})); if(input.recipient && (!input.recipient.name||!input.recipient.address)) items.push(createMissingInfo({category:'recipient',field:'recipient',label:'Complete recipient address',whyItMatters:'A mailing package cannot be safely routed without a complete recipient.',impact:'blocking',suggestedActions:['Use the response-address section of the notice']})); if(input.evidenceCount===0) items.push(createMissingInfo({category:'evidence',field:'supporting_evidence',label:'Supporting evidence',whyItMatters:'The response may need documentation supporting its factual assertions.',impact:'medium',suggestedActions:['Review the case for relevant supporting documents']})); for(const fact of input.facts.filter(f=>!f.verified&&f.confidence<0.9)) items.push(createMissingInfo({category:'evidence',field:`fact_${fact.id}`,label:`Verify: ${fact.label}`,whyItMatters:`This fact has confidence ${fact.confidence}. Verify it against its source before relying on it.`,impact:'medium',suggestedActions:['Compare against the source document','Confirm or correct the value'],relatedFactId:fact.id})); return items; }
export function resolveMissingInfo(item:MissingInfoItem,value:string):MissingInfoItem{return {...item,status:'provided',resolvedValue:value,resolvedAt:new Date().toISOString()};}
export function missingInfoSummary(items:MissingInfoItem[]){return {total:items.length,missing:items.filter(i=>i.status==='missing').length,blocking:items.filter(i=>i.status==='missing'&&i.impact==='blocking').length,provided:items.filter(i=>i.status==='provided').length};}
